### ISSUE TITLE
HTTPS maven

### ISSUE THREAD

**Issue by williewillus** [kvverti/banner-plus-plus#7]
The current maven server given by the readme is on unsecured http, and attempts to connect to it via https fail.

It's 2020, any publicly accessible http endpoint should probably have https on it to prevent malicious code from being mitm-ed onto any consumers of the library, it's free with Let's Encrypt.

**Comment by i509VCB** [comment]
Boundary's maven server should support https per ClientCommands which is on her maven (https://github.com/CottonMC/ClientCommands)?

Edit: It might be the port?

Edit 2: Cotton resources is correct with the URL: https://github.com/CottonMC/CottonResources

**Comment by williewillus** [comment]
The readme says to use 'http://server.bbkr.space:8081/artifactory/libs-release', so it should be updated if that's no the right link
