### ISSUE TITLE
There is no dependency line

### ISSUE THREAD

**Issue by ZestyBlaze** [kvverti/banner-plus-plus#9]
Could you write up the Dependency line that's needed please? It's not in the README file so it's not easy to figure out

So like how we have ```modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"```
Can you write up the one for this mod too?

**Comment by MJRamon** [comment]
It's
```
modImplementation "io.github.fablabsmc:bannerpp:2.0.4+mc.1.17-rc1"
```
(get latest at https://server.bbkr.space/artifactory/libs-release/ )
But lib is outdated for 1.18.*
